substitutions:
  friendly_name: Test Fan
  buzzer_enable: false

button:
  - platform: template
    name: ${friendly_name} Cycle Fan
    on_press:
      then:
        - fan.cycle_speed: the_fan
fan:
  - platform: ifan
    id: the_fan
    name: "${friendly_name} Fan"
    remote_enable: false  
    buzzer_enable: "${buzzer_enable}"

api:
  services:
    - service: fan_cycle
      then:
        - fan.cycle_speed: the_fan
