substitutions:
  friendly_name: Test Fan

external_components:
  - source: github://PartemImperium/esphome_custom_components@master
    refresh: 0s

esphome:
  comment: Sonoff iFan04-L

esp8266:
  board: esp01_1m

packages:
  remote: !include remote.yaml
  fan: !include  fan.yaml
  light: !include light.yaml
  module_light: !include module_light.yaml
  button: !include button.yaml
