substitutions:
  ota_password: password
  # !!!IMPORTANT PROVIDE A VALUE FOR API ENCRYPTION. ENCRYPTION ISNT VERY USEFUL IF THE KEY IS PUBLIC!!!
  # To create a key follow the instructions here https://esphome.io/components/api.html?highlight=api#configuration-variables
  api_encryption: Am3/h7ylK5LGjJcbPobxzH6YiezwEAEZ6UdMMLbVloI=

ota:
  password: ${ota_password}

safe_mode:
  disabled: false
  boot_is_good_after: '1min'
  num_attempts: 10
  reboot_timeout: '5min'

web_server:
  port: 80
  version: 2

api:
  encryption:
    key: ${api_encryption}
