substitutions:
  wifi_password: password
  wifi_ssid: "Wi-Fi ssid"
  friendly_name: "My Device"
  fallback_ap_password: "i am lost"

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: ${fallback_ap_password}

captive_portal: